---
title: "DGE_Acute_Experiment"
author: "Beatriz Silva"
date: "2023-11-06"
output: pdf_document
---


Loading libraries
```{r}

library(edgeR)
library(limma)
library(DESeq2)
library(dplyr)
library(pheatmap)
library(ggplot2)

```


Read files
```{r}

setwd("C:/Users/USUARIO/Desktop/Ude_analysis/Gene_expression/DGE_Chronic_Experiments/DGE_Analysis")

data_counts <- read.table("countData_acute.txt", header = TRUE, sep = "\t", row.names = 1, check.names = FALSE)
sample_info <- read.table("colData_acute.txt", header = TRUE, sep = "\t", row.names = 1, check.names = FALSE)

group <- factor(paste(sample_info$pop, sample_info$temperature, sep="."))
sample_info <- cbind(sample_info, group = group)

# DGEList object

y <- DGEList(counts = data_counts, group = group)

cpm_count <- cpm(y)
  
# thresholds

cpm_Val <- 1   # CPM value threshold
gThreshold <- 5   # At least number of samples threshold

thresholds <- rowSums(cpm_count > cpm_Val) >= gThreshold

y <- calcNormFactors(y, lib.size = T, method = "TMM")

# Apply filtering

y_filter <- y[thresholds,]

# Get CPM values for filtered data (y_filter)

cpm_count_filtered <- cpm(y_filter)

dim(cpm_count_filtered) #  [1] 18509    10

```

```{r}

# Normalized Samples Distribution - Chronic

statuscol <- as.numeric(factor(sample_info$group)) + 1
log_counts <- log(cpm_count_filtered + 1e-02) 

boxplot(log_counts,
        col = statuscol,
        xlab = "", las = 2,
        cex.axis = 0.8, 
        outline = FALSE)
abline(h = median(as.matrix(log_counts)), col = "blue")
title("Normalized Samples Distribution - Acute", cex.main = 0.9)
 

```


```{r}

# MDS plot 

dist_matrix <- 1 - cor(cpm_count_filtered)
mds_result <- cmdscale(dist_matrix, k = 2)
mds_df <- data.frame(Sample = rownames(mds_result), Dim1 = mds_result[, 1], Dim2 = mds_result[, 2])

ggplot(mds_df, aes(x = Dim1, y = Dim2, color = group, label = Sample)) +
  geom_point() +
  geom_text(vjust = -0.5, hjust = 0.5, size = 3) +  
  scale_color_discrete(guide = guide_legend(title = "Groups")) +
  labs(title = "MDS Plot") +
  theme(legend.position = "left", 
        legend.justification = "center",
        plot.title = element_text(hjust = 0.5),
        legend.text = element_text(angle = 0)) +  
  ggtitle("MDS Plot - Acute")

```


EdgeR
```{r}

# Design matrix for glm approach

design <- model.matrix(~sample_info$pop)
rownames(design) <- colnames(y_filter)
yf <- estimateDisp(y_filter, design)
fit <- glmFit(yf, design)

glm <- glmLRT(fit, coef=2)

FDR_chronic_all <- topTags(glm, n = Inf, adjust.method = "BH", sort.by = "none")
FDR_chronic_all <- data.frame(gene_id = rownames(FDR_chronic_all), FDR_chronic_all)
filtered_rows_chronic_all <- FDR_chronic_all[FDR_chronic_all$FDR < 0.05 & abs(FDR_chronic_all$logFC) > 1, ]
DGEs_EdgeR_North_South <- filtered_rows_chronic_all[, c("gene_id", "logFC", "FDR")]

dim(DGEs_EdgeR_North_South)


```
```{r}

plotBCV(yf)

```


limma
```{r}

# design matrix

design <- model.matrix(~sample_info$pop)
rownames(design) <- colnames(y_filter)
y <- voom(y_filter, design, normalize="quantile", plot=T)

# Fitting linear models in limma

fit <- lmFit(y, design)

tmp_all <- contrasts.fit(fit, coef=2)
tmp_all_f <- eBayes(tmp_all)

top.table_all <- topTable(tmp_all_f, number=Inf, adjust="BH", sort.by="none")
FDR_all_df <- data.frame(gene_id = rownames(top.table_all), top.table_all)

DGEs_Limma_North_South <- FDR_all_df[top.table_all$adj.P.Val < 0.05 & abs(top.table_all$logFC ) > 1, ]

dim(DGEs_Limma_North_South) 


```



DESeq2
```{r}

dds <- DESeqDataSetFromMatrix(y_filter$counts, colData = sample_info, design = formula(~pop))

dds <- DESeq(dds, test="Wald")

results_all <- results(dds, contrast=c("pop", "S", "N"))

results_all <- na.omit(results_all)
filter_results_all <- results_all[results_all$padj < 0.05  & abs(results_all$log2FoldChange) > 1 ,]

filter_results_all <- cbind(gene_id = rownames(filter_results_all), filter_results_all)
DGEs_DESeq2_North_South <- filter_results_all[, c("gene_id", "log2FoldChange", "padj")]


dim(DGEs_DESeq2_North_South)   # [1]  1583    3

```
```{r}
plotDispEsts(dds)

```



Overlap 3 methods - North vs South

```{r}

DESeq2 <- DGEs_DESeq2_North_South$gene_id
EdgeR <- DGEs_EdgeR_North_South$gene_id
Limma <- DGEs_Limma_North_South$gene_id

common_rows <- DESeq2[DESeq2 %in% EdgeR & DESeq2 %in% Limma]

common_rows_list <- unlist(common_rows)

overlap_3_methods <- data.frame(gene_id = common_rows_list)

limma_data <- DGEs_Limma_North_South[, c("logFC", "adj.P.Val")]

limma_data$gene_id <- rownames(limma_data)


North_South_overlap <- merge(overlap_3_methods, limma_data, by = "gene_id", all.x = TRUE)

#head(North_South_overlap)

dim(North_South_overlap)

write.table(North_South_overlap, file = "North_South_acute.txt", sep = "\t", quote = FALSE, row.names = FALSE)


```

Data for volcano plots
```{r}

colnames(North_South_overlap) <- c("gene_id", "logFC", "adj.P.Val")

North_South_overlap$diffexpressed <- "NO"

North_South_overlap$diffexpressed[North_South_overlap$logFC > 0.6 & North_South_overlap$adj.P.Val < 0.05] <- "Up regulated"

North_South_overlap$diffexpressed[North_South_overlap$logFC < -0.6 & North_South_overlap$adj.P.Val < 0.05] <- "Down regulated"


# number of DGEs - up and down regulated
up_regulated_count <- sum(North_South_overlap$diffexpressed == "Up regulated")
down_regulated_count <- sum(North_South_overlap$diffexpressed == "Down regulated")
cat("Number of up-regulated genes:", up_regulated_count, "\n")
cat("Number of down-regulated genes:", down_regulated_count, "\n")



```

```{r}

ggplot(data = North_South_overlap, aes(x = logFC, y = -log10(adj.P.Val), col = diffexpressed)) +
  geom_vline(xintercept = c(-0.6, 0.6), col = "gray20", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "gray20", linetype = 'dashed') +
  geom_point(size = 2) +
  scale_color_manual(values = c("#00AFBB", "#bb0c00"), 
                     labels = c("Downregulated", "Upregulated")) +
  xlab(expression(log[2]~Fold~Change)) +
  ylab(expression(-log[10]~padj)) +
  theme_bw() +
  theme(
    axis.line = element_line(color = "black", size = 0.5),  # Customize axis lines
    panel.border = element_blank(),  # Remove plot border
    axis.title = element_text(size = 17),  # Set axis title font size
    legend.title = element_text(size = 14),  # Set legend title font size
    legend.position = "right"  # Move the legend to the right
  ) +
  guides(
    color = guide_legend(title = "Expression Level")  # Customize legend title
  )

```


```{r}

output_data_North_South <- cpm_count_filtered[, grepl("^N45|^S45", colnames(cpm_count_filtered))]

# Add the 'gene_id' column to the output_data matrix
data_gene_id_25 <- cbind(gene_id = rownames(output_data_North_South), output_data_North_South)

# Add the name of the first column: gene_id
names(data_gene_id_25) <- c("gene_id", names(data_gene_id_25)[-1])

# merge the data frames based on the "gene_id" column
merged_df_25 <- merge(data_gene_id_25, North_South_overlap[, c("gene_id", "logFC", "adj.P.Val")], by = "gene_id")

# Selecting the desired columns
final_table_25 <- merged_df_25[, c("gene_id", "N45G1", "N45G2", "N45G3", "N45G4", "N45G5", "S45G1", "S45G2", "S45G3", "S45G4", "S45G5")]

# Convert character matrix to numeric matrix element-wise
numeric_matrix_North_South <- final_table_25[, c( "N45G1", "N45G2", "N45G3", "N45G4", "N45G5", "S45G1", "S45G2", "S45G3", "S45G4", "S45G5")]
numeric_matrix_North_South <- apply(numeric_matrix_North_South, 2, as.numeric)  # Convert each column to numeric

# Set row names
rownames(numeric_matrix_North_South) <- final_table_25$gene_id

# Set column names
colnames(numeric_matrix_North_South) <- c("N45G1", "N45G2", "N45G3", "N45G4", "N45G5", "S45G1", "S45G2", "S45G3", "S45G4", "S45G5")

head(numeric_matrix_North_South)
dim(numeric_matrix_North_South)


```


```{r}


library(gplots)

gene_labels <- rownames(numeric_matrix_North_South)
condition_labels <- colnames(numeric_matrix_North_South)

heatmap.2(numeric_matrix_North_South,
          scale = "row",
          trace = "none",                   
          col = colorRampPalette(colors = c("#273D82", "white", "#C75218"))(100),
          main = "North vs South",
          cex.main = 1,
          Colv = TRUE,                      
          hclustfun = function(c) hclust(c, method = "average"),   
          dendrogram = "column",           
          key = TRUE,
          key.title = " ", 
          key.xlab = "Row Z-Score",    
          margins = c(5, 15),
          cexRow = 0.8,   
          cexCol = 0.8,
          Rowv = TRUE,    
          labRow = FALSE 
)

```


